// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_events.h"
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel26;
extern lv_obj_t *ui_Label23;
extern lv_obj_t *ui_Label24;
extern lv_obj_t *ui_Label25;
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Panel1;
void ui_event_Dropdown2( lv_event_t * e);
extern lv_obj_t *ui_Dropdown2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Label7;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
void ui_event_Checkbox2( lv_event_t * e);
extern lv_obj_t *ui_Checkbox2;
void ui_event_Screen3( lv_event_t * e);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Panel10;
void ui_event_Dropdown1( lv_event_t * e);
extern lv_obj_t *ui_Dropdown1;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Panel13;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Panel14;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Panel15;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Panel16;
extern lv_obj_t *ui_Label13;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label14;
void ui_event_Checkbox1( lv_event_t * e);
extern lv_obj_t *ui_Checkbox1;
void ui_event_Screen4( lv_event_t * e);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_Panel17;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Panel18;
void ui_event_Dropdown3( lv_event_t * e);
extern lv_obj_t *ui_Dropdown3;
extern lv_obj_t *ui_Panel19;
extern lv_obj_t *ui_Panel20;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Panel21;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Panel22;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Panel23;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Panel24;
extern lv_obj_t *ui_Label20;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label21;
void ui_event_Checkbox3( lv_event_t * e);
extern lv_obj_t *ui_Checkbox3;
extern lv_obj_t *ui____initial_actions0;



void MyTask();


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
