// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void ui_event_Screen1( lv_event_t * e);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel26;
lv_obj_t *ui_Label23;
lv_obj_t *ui_Label24;
lv_obj_t *ui_Label25;
void ui_event_Screen2( lv_event_t * e);
lv_obj_t *ui_Screen2;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Panel1;
void ui_event_Dropdown2( lv_event_t * e);
lv_obj_t *ui_Dropdown2;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Panel8;
lv_obj_t *ui_Label7;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Checkbox2;
void ui_event_Screen3( lv_event_t * e);
lv_obj_t *ui_Screen3;
lv_obj_t *ui_Panel9;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Panel10;
void ui_event_Dropdown1( lv_event_t * e);
lv_obj_t *ui_Dropdown1;
lv_obj_t *ui_Panel11;
lv_obj_t *ui_Panel12;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Panel13;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Panel14;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Panel15;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Panel16;
lv_obj_t *ui_Label13;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label14;
void ui_event_Checkbox1( lv_event_t * e);
lv_obj_t *ui_Checkbox1;
void ui_event_Screen4( lv_event_t * e);
lv_obj_t *ui_Screen4;
lv_obj_t *ui_Panel17;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Panel18;
void ui_event_Dropdown3( lv_event_t * e);
lv_obj_t *ui_Dropdown3;
lv_obj_t *ui_Panel19;
lv_obj_t *ui_Panel20;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Panel21;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Panel22;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Panel23;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Panel24;
lv_obj_t *ui_Label20;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label21;
void ui_event_Checkbox3( lv_event_t * e);
lv_obj_t *ui_Checkbox3;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
      _ui_screen_change( ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
}
void ui_event_Screen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
      _ui_screen_change( ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
      _ui_screen_change( ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
}
void ui_event_Dropdown2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      ( e );
}
}
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      ( e );
}
}
void ui_event_Screen3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
      _ui_screen_change( ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
      _ui_screen_change( ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
}
void ui_event_Dropdown1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      ( e );
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      ( e );
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      ( e );
}
}
void ui_event_Checkbox1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      ( e );
}
}
void ui_event_Screen4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
      _ui_screen_change( ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
      _ui_screen_change( ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
}
void ui_event_Dropdown3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      ( e );
}
}
void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      ( e );
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      ( e );
}
}
void ui_event_Checkbox3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      ( e );
}
}

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel26 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel26, 513);
lv_obj_set_height( ui_Panel26, 96);
lv_obj_set_x( ui_Panel26, -44 );
lv_obj_set_y( ui_Panel26, -74 );
lv_obj_set_align( ui_Panel26, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Panel26, lv_color_hex(0xE95053), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel26, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label23 = lv_label_create(ui_Panel26);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label23, 45 );
lv_obj_set_y( ui_Label23, -6 );
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"Welcome to the intelligent \nwarehouse control system");
lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x06D74B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label24 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label24, -27 );
lv_obj_set_y( ui_Label24, -6 );
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"This is a demo of the Factory IO");

ui_Label25 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label25, -74 );
lv_obj_set_y( ui_Label25, 26 );
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"Designer : ShaoLu");

lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel2 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel2, lv_pct(104));
lv_obj_set_height( ui_Panel2, lv_pct(107));
lv_obj_set_y( ui_Panel2, -2 );
lv_obj_set_x( ui_Panel2, lv_pct(0) );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -2 );
lv_obj_set_y( ui_Label2, -97 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Warehouse 1 Debugging");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel1, 356);
lv_obj_set_height( ui_Panel1, 106);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, -23 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Dropdown2 = lv_dropdown_create(ui_Panel1);
lv_dropdown_set_options( ui_Dropdown2, "Material Conveyor 1\nMaterial Conveyor 2\nMaterial Conveyor 3\nBOX Conveyor 1\nBOX Conveyor 2\nBOX Conveyor 3\nBOX Conveyor 4\nBOX Conveyor 5\n\n" );
lv_obj_set_width( ui_Dropdown2, 178);
lv_obj_set_height( ui_Dropdown2, 36);
lv_obj_set_x( ui_Dropdown2, -63 );
lv_obj_set_y( ui_Dropdown2, -21 );
lv_obj_set_align( ui_Dropdown2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Dropdown2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel3, 356);
lv_obj_set_height( ui_Panel3, 80);
lv_obj_set_x( ui_Panel3, 4 );
lv_obj_set_y( ui_Panel3, 75 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_scrollbar_mode(ui_Panel3, LV_SCROLLBAR_MODE_ON);

ui_Panel4 = lv_obj_create(ui_Panel3);
lv_obj_set_width( ui_Panel4, 175);
lv_obj_set_height( ui_Panel4, 46);
lv_obj_set_x( ui_Panel4, -222 );
lv_obj_set_y( ui_Panel4, 0 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Material sensor 1");

ui_Panel5 = lv_obj_create(ui_Panel3);
lv_obj_set_width( ui_Panel5, 175);
lv_obj_set_height( ui_Panel5, 46);
lv_obj_set_x( ui_Panel5, -222 );
lv_obj_set_y( ui_Panel5, 0 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Material sensor 2");

ui_Panel6 = lv_obj_create(ui_Panel3);
lv_obj_set_width( ui_Panel6, 175);
lv_obj_set_height( ui_Panel6, 46);
lv_obj_set_x( ui_Panel6, -222 );
lv_obj_set_y( ui_Panel6, 0 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"BOX sensor 1");

ui_Panel7 = lv_obj_create(ui_Panel3);
lv_obj_set_width( ui_Panel7, 175);
lv_obj_set_height( ui_Panel7, 46);
lv_obj_set_x( ui_Panel7, -222 );
lv_obj_set_y( ui_Panel7, 0 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"BOX sensor 2");

ui_Panel8 = lv_obj_create(ui_Panel3);
lv_obj_set_width( ui_Panel8, 175);
lv_obj_set_height( ui_Panel8, 46);
lv_obj_set_x( ui_Panel8, -222 );
lv_obj_set_y( ui_Panel8, 0 );
lv_obj_set_align( ui_Panel8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_Panel8);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"BOX sensor 3");

ui_Button1 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 77);
lv_obj_set_x( ui_Button1, 91 );
lv_obj_set_y( ui_Button1, -31 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button1, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xEEED32), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"TEST");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Checkbox2 = lv_checkbox_create(ui_Screen2);
lv_checkbox_set_text(ui_Checkbox2,"Enable");
lv_obj_set_width( ui_Checkbox2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox2, -67 );
lv_obj_set_y( ui_Checkbox2, 1 );
lv_obj_set_align( ui_Checkbox2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Checkbox2, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel9 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel9, lv_pct(104));
lv_obj_set_height( ui_Panel9, lv_pct(107));
lv_obj_set_y( ui_Panel9, -2 );
lv_obj_set_x( ui_Panel9, lv_pct(0) );
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x2BED57), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -2 );
lv_obj_set_y( ui_Label8, -97 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Warehouse 2 Debugging");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel10 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel10, 356);
lv_obj_set_height( ui_Panel10, 106);
lv_obj_set_x( ui_Panel10, 0 );
lv_obj_set_y( ui_Panel10, -23 );
lv_obj_set_align( ui_Panel10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Dropdown1 = lv_dropdown_create(ui_Panel10);
lv_dropdown_set_options( ui_Dropdown1, "Material Conveyor 1\nMaterial Conveyor 2\nMaterial Conveyor 3\nBOX Conveyor 1\nBOX Conveyor 2\nBOX Conveyor 3\nBOX Conveyor 4\nBOX Conveyor 5\n\n" );
lv_obj_set_width( ui_Dropdown1, 178);
lv_obj_set_height( ui_Dropdown1, 36);
lv_obj_set_x( ui_Dropdown1, -63 );
lv_obj_set_y( ui_Dropdown1, -21 );
lv_obj_set_align( ui_Dropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel11 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel11, 356);
lv_obj_set_height( ui_Panel11, 80);
lv_obj_set_x( ui_Panel11, 4 );
lv_obj_set_y( ui_Panel11, 75 );
lv_obj_set_align( ui_Panel11, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel11,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_scrollbar_mode(ui_Panel11, LV_SCROLLBAR_MODE_ON);

ui_Panel12 = lv_obj_create(ui_Panel11);
lv_obj_set_width( ui_Panel12, 175);
lv_obj_set_height( ui_Panel12, 46);
lv_obj_set_x( ui_Panel12, -222 );
lv_obj_set_y( ui_Panel12, 0 );
lv_obj_set_align( ui_Panel12, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_Panel12);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Material sensor 1");

ui_Panel13 = lv_obj_create(ui_Panel11);
lv_obj_set_width( ui_Panel13, 175);
lv_obj_set_height( ui_Panel13, 46);
lv_obj_set_x( ui_Panel13, -222 );
lv_obj_set_y( ui_Panel13, 0 );
lv_obj_set_align( ui_Panel13, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label10 = lv_label_create(ui_Panel13);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Material sensor 2");

ui_Panel14 = lv_obj_create(ui_Panel11);
lv_obj_set_width( ui_Panel14, 175);
lv_obj_set_height( ui_Panel14, 46);
lv_obj_set_x( ui_Panel14, -222 );
lv_obj_set_y( ui_Panel14, 0 );
lv_obj_set_align( ui_Panel14, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_Panel14);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"BOX sensor 1");

ui_Panel15 = lv_obj_create(ui_Panel11);
lv_obj_set_width( ui_Panel15, 175);
lv_obj_set_height( ui_Panel15, 46);
lv_obj_set_x( ui_Panel15, -222 );
lv_obj_set_y( ui_Panel15, 0 );
lv_obj_set_align( ui_Panel15, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_Panel15);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"BOX sensor 2");

ui_Panel16 = lv_obj_create(ui_Panel11);
lv_obj_set_width( ui_Panel16, 175);
lv_obj_set_height( ui_Panel16, 46);
lv_obj_set_x( ui_Panel16, -222 );
lv_obj_set_y( ui_Panel16, 0 );
lv_obj_set_align( ui_Panel16, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label13 = lv_label_create(ui_Panel16);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"BOX sensor 3");

ui_Button2 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button2, 100);
lv_obj_set_height( ui_Button2, 77);
lv_obj_set_x( ui_Button2, 91 );
lv_obj_set_y( ui_Button2, -31 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button2, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xEEED32), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"TEST");
lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Checkbox1 = lv_checkbox_create(ui_Screen3);
lv_checkbox_set_text(ui_Checkbox1,"Enable");
lv_obj_set_width( ui_Checkbox1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox1, -67 );
lv_obj_set_y( ui_Checkbox1, 1 );
lv_obj_set_align( ui_Checkbox1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Checkbox1, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox1, ui_event_Checkbox1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel17 = lv_obj_create(ui_Screen4);
lv_obj_set_width( ui_Panel17, lv_pct(104));
lv_obj_set_height( ui_Panel17, lv_pct(107));
lv_obj_set_y( ui_Panel17, -2 );
lv_obj_set_x( ui_Panel17, lv_pct(0) );
lv_obj_set_align( ui_Panel17, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x4881FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_Panel17);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -2 );
lv_obj_set_y( ui_Label15, -97 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Warehouse 3 Debugging");
lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel18 = lv_obj_create(ui_Screen4);
lv_obj_set_width( ui_Panel18, 356);
lv_obj_set_height( ui_Panel18, 106);
lv_obj_set_x( ui_Panel18, 0 );
lv_obj_set_y( ui_Panel18, -23 );
lv_obj_set_align( ui_Panel18, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Dropdown3 = lv_dropdown_create(ui_Panel18);
lv_dropdown_set_options( ui_Dropdown3, "Material Conveyor 1\nMaterial Conveyor 2\nMaterial Conveyor 3\nBOX Conveyor 1\nBOX Conveyor 2\nBOX Conveyor 3\nBOX Conveyor 4\nBOX Conveyor 5\n\n" );
lv_obj_set_width( ui_Dropdown3, 178);
lv_obj_set_height( ui_Dropdown3, 36);
lv_obj_set_x( ui_Dropdown3, -63 );
lv_obj_set_y( ui_Dropdown3, -21 );
lv_obj_set_align( ui_Dropdown3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Dropdown3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel19 = lv_obj_create(ui_Screen4);
lv_obj_set_width( ui_Panel19, 356);
lv_obj_set_height( ui_Panel19, 80);
lv_obj_set_x( ui_Panel19, 4 );
lv_obj_set_y( ui_Panel19, 75 );
lv_obj_set_align( ui_Panel19, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel19,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel19, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_scrollbar_mode(ui_Panel19, LV_SCROLLBAR_MODE_ON);

ui_Panel20 = lv_obj_create(ui_Panel19);
lv_obj_set_width( ui_Panel20, 175);
lv_obj_set_height( ui_Panel20, 46);
lv_obj_set_x( ui_Panel20, -222 );
lv_obj_set_y( ui_Panel20, 0 );
lv_obj_set_align( ui_Panel20, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel20, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label16 = lv_label_create(ui_Panel20);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"Material sensor 1");

ui_Panel21 = lv_obj_create(ui_Panel19);
lv_obj_set_width( ui_Panel21, 175);
lv_obj_set_height( ui_Panel21, 46);
lv_obj_set_x( ui_Panel21, -222 );
lv_obj_set_y( ui_Panel21, 0 );
lv_obj_set_align( ui_Panel21, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel21, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label17 = lv_label_create(ui_Panel21);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"Material sensor 2");

ui_Panel22 = lv_obj_create(ui_Panel19);
lv_obj_set_width( ui_Panel22, 175);
lv_obj_set_height( ui_Panel22, 46);
lv_obj_set_x( ui_Panel22, -222 );
lv_obj_set_y( ui_Panel22, 0 );
lv_obj_set_align( ui_Panel22, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel22, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label18 = lv_label_create(ui_Panel22);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"BOX sensor 1");

ui_Panel23 = lv_obj_create(ui_Panel19);
lv_obj_set_width( ui_Panel23, 175);
lv_obj_set_height( ui_Panel23, 46);
lv_obj_set_x( ui_Panel23, -222 );
lv_obj_set_y( ui_Panel23, 0 );
lv_obj_set_align( ui_Panel23, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel23, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label19 = lv_label_create(ui_Panel23);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"BOX sensor 2");

ui_Panel24 = lv_obj_create(ui_Panel19);
lv_obj_set_width( ui_Panel24, 175);
lv_obj_set_height( ui_Panel24, 46);
lv_obj_set_x( ui_Panel24, -222 );
lv_obj_set_y( ui_Panel24, 0 );
lv_obj_set_align( ui_Panel24, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel24, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label20 = lv_label_create(ui_Panel24);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"BOX sensor 3");

ui_Button3 = lv_btn_create(ui_Screen4);
lv_obj_set_width( ui_Button3, 100);
lv_obj_set_height( ui_Button3, 77);
lv_obj_set_x( ui_Button3, 91 );
lv_obj_set_y( ui_Button3, -31 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button3, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xEEED32), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label21 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"TEST");
lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Checkbox3 = lv_checkbox_create(ui_Screen4);
lv_checkbox_set_text(ui_Checkbox3,"Enable");
lv_obj_set_width( ui_Checkbox3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox3, -67 );
lv_obj_set_y( ui_Checkbox3, 1 );
lv_obj_set_align( ui_Checkbox3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_Checkbox3, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Dropdown3, ui_event_Dropdown3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Checkbox3, ui_event_Checkbox3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen3_screen_init();
ui_Screen4_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
